### PR TITLE
chore: fixing esm

### PR DESCRIPTION
**Pull request by yordis**

### CODE REVIEW

**Comment by frank-dspeed** [comment]
module: nodenext should be esnext in your tsconfig as nodenext and node12 are already outdated even by current nodejs as it already supports es2022 partial going with esnext is the most simple typescript will simply not change your written code thats always a good thing to depend on. 

https://www.typescriptlang.org/tsconfig#module

**Comment by yordis** [comment]
@frank-dspeed fixed here https://github.com/straw-hat-team/nodejs-monorepo/pull/24


... hopefully Jest catch up with all these ESM mess, really painful right now

**Comment by frank-dspeed** [comment]
@yordis maybe switch to ava it should be all you need and works great

**Comment by yordis** [comment]
@frank-dspeed I would replace it, but we have way too much dependency with Jest from our NextJS apps, so I will be kicking the can not that far away.

Are you involved in the NextJS ecosystem? If so, what do you use for testing?

**Comment by frank-dspeed** [comment]
@yordis can you point me to some example tests there are many types of tests i my self write all my code with tests inside it self i do real assert calls in the runtime code and later for production i transpil that away

but i got integration tests so one level over that and there i use simply chromium --headless directly. If i want to do really big tests i throw in Selenium.

out of my history i learned functions that do work are greate but  most errors happen on the integration side. And when the Whole Integration works then the unit works also that is verifyed.

**Comment by yordis** [comment]
@frank-dspeed I lost track of the situation of ESM and TypeScript and whatnot. Do you think it is a good time for me to come back to the topic?

**Comment by frank-dspeed** [comment]
in general if you use current node there is nothing blocking you as npm got a new workspaces feature that solves a lot of problems.

**Comment by yordis** [comment]
Right now, everything is at least `Node 16.15.0 LTS`, is that what you mean by "current"?

**Comment by yordis** [comment]
The other problems I am facing are related to Jest and NextJS btw, driving my nuts.

**Comment by frank-dspeed** [comment]
@yordis yes that is current but you should upgrade npm regulary via npm -i -g npm@latest

**Comment by frank-dspeed** [comment]
@yordis maybe point me to some of your issues i can then init some PR's with explainers. to solve them

**Comment by yordis** [comment]
@frank-dspeed yeah yeah, let me fix the https://github.com/straw-hat-team/nextjs-starter-kit repo and add some basic tests to show the problems.

Thank you so much for your help though! You are the best!

**Pull request closed without merging**
